export const texts = {
    de: {
        section1H:  "Hallo!",
        section1:   "Wir sind ein Forschungsteam aus vier Personen und möchten die Rolle des Faktors Mensch in der Softwareentwicklung untersuchen. In dieser Studie möchten wir speziell über Autismus im Entwicklungsprozess forschen. Zu unserem Team gehören Prof. Dr. Dipl.-Psych Janet Siegmund, Prof. Dr. Sven Apel, Prof. Dr. Isabella Graßl und Nadja/ Felis Just. Ihre Perspektive ist dabei zentral. Durch den direkten Austausch möchten wir gemeinsam ein Bild der Arbeitssituation autistischer Entwickler*innen zeichnen, das auf den eigenen Stimmen beruht und als Grundlage für sinnvolle Veränderungen dienen kann. Dieser mehrstufige Prozess beginnt mit Interviews mit autistischen Entwickler*innen.",
        section2H:  "Inhalt und Ablauf",
        section2:   "In dem Interview möchten wir über Themen sprechen, die Sie im Zusammenhang mit Ihrer Arbeit in der Softwareentwicklung für wichtig halten. Außerdem möchten wir Ihnen einige Fragen stellen, bei denen uns Ihre persönliche Perspektive interessiert. Für das Interview bitten wir Sie, einen Fragebogen auszufüllen. Das Interview wird so gegliedert sein, dass wir zuerst über die Themen im Fragebogen sprechen. Sie können ebenfalls gern eigene Themen ansprechen, die Sie für die Softwareentwicklung als wichtig erachten. Unser Ziel ist es zu erfahren, welche Stärken Sie in den Entwicklungsprozess einbringen können und welchen Herausforderungen sie begegnen. Anschließend würden wir gern Ihre Betrachtungen zu den eingesetzten Tools und Methoden vertiefen und wissen, wie sie den Entwicklungsprozess von Software allgemein sehen und planen.",
        section3H:  "Eingesetzte Technik und Datensicherheit",
        section3:   "Der Fragebogen wurde mit einer von der Technischen Universität Chemnitz gehosteten LimeSurvey Instanz erstellt. In diesem geht es um Ihre Programmiererfahrungen und Ihre Meinung zu bekannten Entwicklungsprozessen und -tools. Bitte senden Sie uns den ausgefüllten Bogen vor dem Interview zurück. So können wir uns optimal auf das Gespräch vorbereiten." + "Das Interview selbst kann in Präsenz oder Online stattfinden. Das Online-Meeting können wir über die von der Technischen Universität Chemnitz gehosteten Videokonferenz Software BigBlueButton abhalten. Das Interview selbst wird etwa eine halbe Stunde dauern. Mit Ihrer Zustimmung würden wir das Gespräch gern aufzeichnen. Sollte Ihnen das nicht recht sein, verzichten wir selbstverständlich darauf. Die Aufzeichnungen Ihres Interviews werden wir von der Software f4x automatisch transkribieren lassen. Die von Ihnen erhobenen Daten im Vorabfragebogen, Notizen aus dem Interview und insofern sie einer Aufzeichnung zustimmen, die Daten der Aufzeichnung werden von uns anonymisiert und DSGVO-konform gespeichert und verarbeitet. Sollten in dem Interview identifizierende Informationen vorkommen, wie zum Beispiel ehemalige Arbeitgeber, werden wir diese ebenfalls entfernen. Das bedeutet: Ihre Antworten können nicht auf Sie als Person zurückgeführt werden.",
        section4H:  "Verwendung der Daten",
        section4:   "Die gewonnenen Erkenntnisse möchten wir anschließend in wissenschaftlichen Arbeiten veröffentlichen. In dieser Arbeit werden wir nur abstrahiert über die Erkenntnisse aus den Interviews schreiben. Einzelne Antworten oder persönliche Daten werden nicht veröffentlicht. Wir werden ebenfalls die Aufzeichnungen der Interviews nicht veröffentlichen und nach der Transkription löschen. Bis zur Veröffentlichung haben Sie das Recht, der Nutzung Ihrer Daten zu widersprechen. In diesem Fall werden wir Ihre Daten umgehend löschen.",
        section5H:  "Hilfsmittel",
        section5:   "Uns ist wichtig, das Interview so angenehm wie möglich für Sie zu gestalten. Wenn es bestimmte Techniken oder Hilfsmittel gibt, die Sie im Interview gerne nutzen möchten, zum Beispiel Kommunikationskarten oder ein Stressbarometer, teilen Sie uns das bitte vorab mit.",
        section6H:  "Kontakt",
        section6:   "Haben Sie noch Fragen zum Interview, zur Situation oder zum Ablauf? Wir freuen uns, von Ihnen zu hören."
    },

    eng:{
        section1H:  "Hello!",
        section1:   "We are a research team of four people and aim to investigate the role of the human factor in software development. In this study, we specifically focus on researching autism in the development process. Our team consists of Prof. Dr. Dipl.-Psych. Janet Siegmund, Prof. Dr. Sven Apel, Prof. Dr. Isabella Graßl, and Nadja/Felis Just. Your perspective is central to this research. Through direct exchange, we aim to jointly develop an understanding of the working situation of autistic developers that is based on their own voices and can serve as a foundation for meaningful change. This multi-stage process begins with interviews with autistic developers.",
        section1Img: "",
        section2H:  "Content and procedure",
        section2:   "In the interview, we would like to talk about topics that you consider important in relation to your work in software development. In addition, we would like to ask you some questions in which we are particularly interested in your personal perspective. For the interview, we ask you to complete a questionnaire in advance. The interview will be structured such that we first discuss the topics covered in the questionnaire. You are also very welcome to raise your own topics that you consider important for software development. Our goal is to understand which strengths you contribute to the development process and which challenges you encounter. Afterwards, we would like to explore your views on the tools and methods used and learn how you generally perceive and plan the software development process.",
        section3H:  "Technology used and data protection",
        section3:   "The questionnaire was created using a LimeSurvey instance hosted by University of Technology Chemnitz. It addresses your programming experience and your opinions on well-known development processes and tools. Please send the completed questionnaire back to us before the interview so that we can prepare optimally for the conversation. The interview itself can take place either in person or online. The online meeting can be conducted via the BigBlueButton video conferencing software hosted by University of Technology Chemnitz. The interview will last approximately half an hour. With your consent, we would like to record the interview. If you do not agree to this, we will of course refrain from doing so. The recordings of your interview will be automatically transcribed using the software f4x. The data collected in the preliminary questionnaire, notes from the interview, and, if you consent to recording, the data from the recording will be anonymized and stored and processed in compliance with the GDPR. If identifying information appears in the interview, such as former employers, we will also remove this information. This means that your responses cannot be traced back to you as an individual.",
        section4H:  "Data usage",
        section4:   "We intend to publish the findings in scientific publications. In these works, we will only report on the insights from the interviews in an abstracted manner. Individual responses or personal data will not be published. We will also not publish the interview recordings and will delete them after transcription. Until publication, you have the right to withdraw your consent to the use of your data. In this case, we will delete your data immediately.",
        section5H:  "Aids",
        section5:   "It is important to us to make the interview as comfortable as possible for you. If there are specific techniques or aids you would like to use during the interview, for example, communication cards or a stress barometer, please let us know in advance.",
        section6H:  "Contact",
        section6:   "Do you have any questions about the interview, the situation, or the procedure? We look forward to hearing from you."
    }
}